# Generated by Django 5.2.1 on 2026-01-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="club",
            name="files",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
