# Generated by Django 5.2.1 on 2026-02-01 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0002_club_content_club_files"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clubpost",
            name="file",
        ),
        migrations.RemoveField(
            model_name="clubpost",
            name="image",
        ),
        migrations.RemoveField(
            model_name="clubpost",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="clubpost",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="clubpost",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
